version: '3.7'
services:
  backend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
    command: sh -c "yarn && yarn dev"
    depends_on:
      - db

  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn start"
    depends_on:
      - backend

  db:
    image: bitnami/mongodb:5.0
    volumes:
      - ./docker/mongodb:/bitnami/mongodb
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=tweetulator
      - ALLOW_EMPTY_PASSWORD=yes
